src/common/helpers/redis-helper.ts, src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts, src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts, src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
Fixes #
- Updated lambda policies and log bucket name
- Updated redis port number
---
=> feat(bugfix): Bug/bucket name

README.md
=> feat(documentation): add badges

DEVELOPER_GUIDE.md, README.md, src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/README.md
Fixes #130 
- Update README to address the minimum deployable pattern definition issue
- Update developer guide with correct minimal versions of deps
- Add Getting Started instructions
---
=> feat(doc): fix documentation

src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md, src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts, test/patterns/gen-ai/aws-qa-appsync-opensearch/aws-qa-appsync-opensearch.test.ts
=> feat: qa concurrency props

README.md
Fixes #
Add link to official samples repo
---
=> feat(doc): update readme with additional resources

src/common/helpers/s3-bucket-helper.ts
Remove console logging statements.
---
=> fix: remove console log statements

README.md
Remove duplicated section from the readme
---
=> fix(doc): Update README.md

src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md
Fix image not displayed
Fixes #
---
=> chore(doc): Update README_custom_sagemaker_endpoint.md

test/common/helpers/utils.test.ts
A better description of the tests and annotation for the comments
---
=> fix: update lambdaMemorySizeLimiter title and comments

.projen/deps.json, .projenrc.ts, CHANGELOG.md, package.json, yarn.lock
Updates to recent version of the CDK
---
=> fix: update cdk lib to 2.116.0

lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/helper.py, lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py, src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts, src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
Update AOSS Resources
This PR contains fixes for:
- Updating value of resource element for 'aoss:APIAccessAll'
- Updating OpenSearch Serverless mappings
- Updating opensearch_url for aoss
These changes will ensure the AOSS resources are up to date and configured properly.
---
=> fix: update aoss resources

lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py, lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/chain.py, lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/helper.py, lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt, lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/helpers/opensearch_helper.py, lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py, lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/requirements.txt, lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt, lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt, lambda/aws-summarization-appsync-stepfn/summary_generator/lambda.py, lambda/aws-summarization-appsync-stepfn/summary_generator/requirements.txt, layers/langchain-common-deps/requirements.txt, layers/langchain-common-layer/python/genai_core/adapters/base/base.py, src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts, src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
chore(deps): upgrade dependencies
---
=> chore(deps): upgrade dependencies

README.md
Update main README with new additional resources
Requires https://github.com/aws-samples/aws-genai-llm-chatbot/pull/343 to be merged first
---
=> chore(doc): update documentation with new resources

.github/workflows/code-generation.yml, .projen/tasks.json, .projenrc.ts, projenrc/github-workflows.ts
Fixes #
- Update the code generation task to also run the post compile step and generate the associated updated api docs changes if any is necessary
- fix typo in workflow file which prevents the if statement from working properly
---
=> chore(github): update github workflow

lambda/aws-contentgen-appsync-lambda/src/requirements.txt
Fixes #
1. updated requirement.txt file with proper condition. 
---
=> feat(bugfix): fixed version error

.github/workflows/code-generation.yml, .github/workflows/upgrade-main.yml, projenrc/github-jobs.ts, projenrc/github-workflows.ts
Fixes #
Update PAT used for auto generated PRs 
---
=> chore(github): change PAT used for workflows

.github/workflows/bandit.yml, .github/workflows/build.yml, .github/workflows/code-generation.yml, .github/workflows/commitlint.yml, .github/workflows/deploydocs.yml, .github/workflows/ort-toolkit.yml, .github/workflows/release.yml, .github/workflows/semgrep.yml, .github/workflows/testdeployment.yml, .github/workflows/upgrade-main.yml, .projenrc.ts, projenrc/github-jobs.ts, projenrc/github-workflows.ts
=> fix: update actions with deprecation notice for node v16

lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt, lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt
=> fix(deps): dependencies

src/cdk-lib/bedrock/README.md
Fixes #428 
Fix documentation for add alias code snippet in Python
---
=> fix(documentation): update python code snippet for agent alias

apidocs/classes/bedrock.BedrockFoundationModel.md, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/titan.py, lambda/aws-qa-appsync-opensearch/question_answering/src/llms/types.py, src/cdk-lib/bedrock/models.ts
Fixes #
https://aws.amazon.com/blogs/aws/build-rag-and-agent-based-generative-ai-applications-with-new-amazon-titan-text-premier-model-available-in-amazon-bedrock/
---
=> chore(model): add support for titan premier

DEVELOPER_GUIDE.md
=> chore(docs): update DEVELOPER_GUIDE.md

src/cdk-lib/bedrock/README.md
Fixes #
Fixe code snippet for agent action group in Python
---
=> chore(doc): fix code snippet

README.md
=> chore(readme): add additional resources

lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt, lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/requirements.txt, lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt, lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt, lambda/aws-summarization-appsync-stepfn/summary_generator/requirements.txt, layers/langchain-common-deps/requirements.txt
Fixes #
Fixes dependabot issues for current version of langchain community used
updating to latest version https://github.com/langchain-ai/langchain/releases/tag/langchain-community%3D%3D0.2.5
---
=> chore(deps): update langchain community

.github/dependabot.yml, .projenrc.ts
Fixes #
Add auto-approve label to dependabot PRs
---
=> chore(actions): label dependabot PRs

package.json, yarn.lock
Reverts awslabs/generative-ai-cdk-constructs#530
Breaks the build
=> Revert "chore(deps): upgrade dependencies"

lambda/aws-qa-appsync-opensearch/question_answering/src/llms/types.py
Fixes #
Add support for claude sonnet 3.5 in qa construct
---
=> chore(bedrock): add support for claude sonnet 3.5 in qa

src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
=> feat(bugfix): updated maxlength value from 32 to 63

lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/helpers/utils.py
Fixes https://github.com/aws-samples/generative-ai-cdk-constructs-samples/issues/99
Add path to join.
Ingesting:
---
=> fix: update path to upload file

.projenrc.ts, README.md, package.json
Adds the proper package name for use.
---
=> fix: add package name for Go module

lambda/aws-text-to-sql/query_executor/db_helper.py, lambda/aws-text-to-sql/query_generator/db_helper.py
Fixes findings for text to sql from codeql https://github.com/awslabs/generative-ai-cdk-constructs/security/code-scanning
---
=> chore(texttosql): codeql findings

apidocs/namespaces/bedrock/enumerations/PiiEntitiesConfigAction.md, apidocs/namespaces/bedrock/interfaces/GuardrailProps.md, src/cdk-lib/bedrock/guardrails.ts, src/cdk-lib/bedrock/pii-list.ts
=> fix(guardrail): replace mask for anonymize

README.md
Fixes #
Update readme to add new additional resource (workshop)
---
=> chore(readme): add new additional resource

apidocs/classes/WebCrawler.md, src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts, src/patterns/gen-ai/aws-web-crawler/index.ts
=> fix(deprecation): announce deprecation of some constructs

apidocs/namespaces/opensearchserverless/enumerations/TokenFilterType.md, apidocs/namespaces/opensearchserverless/enumerations/TokenizerType.md, src/cdk-lib/opensearchserverless/analysis-plugins.ts
=> feat(oss): add nori identifiers

apidocs/@cdklabs/namespaces/bedrock/classes/BedrockFoundationModel.md, src/cdk-lib/bedrock/models.ts
Fixes #
Add new models to the list
---
=> chore(deps): add models

apidocs/@cdklabs/namespaces/bedrock/classes/BedrockFoundationModel.md, src/cdk-lib/bedrock/models.ts
=> chore(models): add claude 4 models
