awslabs/generative-ai-cdk-constructs

src/common/helpers/utils.ts, src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts, src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
When tearing down/re-deploying a stack using the constructs, the user can face an issue where 
```
"Invalid Logging Configuration: The CloudWatch Logs Resource Policy size was exceeded. We suggest prefixing your CloudWatch log group name with /aws/vendedlogs/states/. (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidLoggingConfiguration; Request ID: ccf12a8e-30f5-4cc5-a4a2-627850477782; Proxy: null)" (RequestToken: 1a8e1d6a-162b-df56-7e6c-b04d222b7765, HandlerErrorCode: InvalidRequest)". 
```
This is related to an issue in IH where a log delivery policy is created (AWSLogDeliveryWrite*) and data are cumulated without being properly cleared. One way to workaround the issue is to prefix the name of the log group however that api [is not …
=> fix(constructs): fix log group name bug for step functions

layers/langchain-common-deps/requirements.txt
Docs no longer support langchain 0.0.329
Fixes #
---
=> chore: upgrading package versions

.gitignore, .npmignore, .projen/deps.json, .projen/tasks.json, .projenrc.ts, package.json, tsconfig.dev.json, yarn.lock
Projen 0.78.9 fixes the warning:
> (WARN) Define `ts-jest` config under `globals` is deprecated
---
=> fix: ts-jest configuration under globals

.projen/deps.json, .projen/tasks.json, .projenrc.ts, package.json, yarn.lock
Because husky is only needed for local development remove the husky installation when packaging.
---
=> fix: do not require husky downstream

src/common/helpers/utils.ts, test/common/helpers/utils.test.ts
Resources for #169 need physical names shorter than 32 characters with only lowercase letters, numbers, and hyphens. This change preserves existing behavior as much as possible.
When `maxLength` is greater than `prefixLength` + `stackIdGuidLength`
+ 3, the original algorithm is used. Otherwise, a new algorithm is used that requires an `IConstruct` for the stack name and node unique id.
An optional boolean parameter `lower` was added. When true, `allParts` ias also made lower case.
It throws errors if the resulting name is longer than `maxLength` or if `resource` is needed by not provided.
Fixes #195
---
=> fix(utils): generatephysicalname handles short names

src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
Updates the README for using the GraphQL enumeration instead of `String`
---
=> fix(documentation): use enum for responseGenerationMethod in example

lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/chain.py, lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/helper.py, lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py, src/common/helpers/appsyncmergedapi-helper.ts, src/common/helpers/opensearch-helper.ts, src/patterns/gen-ai/aws-langchain-common-layer/README.md, src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md, src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts, src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/README.md, src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts, src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts, test/patterns/gen-ai/aws-qa-appsync-opensearch/aws-qa-appsync-opensearch-serverless.test.ts, test/patterns/gen-ai/aws-qa-appsync-opensearch/aws-qa-appsync-opensearch.test.ts, test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch-serverless.test.ts, test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch.test.ts
Fixes # 136
This PR adds an existingOpensearchServerlessCollection option to support importing existing OpenSearch Serverless collections.
---
=> feat: implement opensearch serverless support

src/patterns/gen-ai/aws-langchain-common-layer/README.md, src/patterns/gen-ai/aws-langchain-common-layer/index.ts, test/patterns/gen-ai/aws-langchain-common-layer/aws-langchain-common-layer.test.ts
Fixes a bug in the Lambda Layer construct (regression) where the path to the asset is wrong, preventing correct deployment
- fix path
- fix documentation
- add tests to prevent regression in future releases
Tested manually in Typescript and Python to make sure it synths correctly
---
=> fix(lambda layer): fix wrong path preventing deployment

apidocs/classes/bedrock.Agent.md, src/cdk-lib/bedrock/agent.ts, test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap
Fixes #229 
This change makes `changeIds` and `prepareAgent` private fields of agent and adds a public, but internal method named `_addPrepareAgentDependency` to resources created after the Agent, such as an upcoming Action Group, can be dependencies of the PrepareAgent custom resource.
Changes
* Moves the PrepareAgent custom resource to earlier in the file so the Agent and KB Associations can use  the method.
* Use the new method to make the agent and KB association custom resources dependencies of prepareAgent.
* Make prepareAgent a dependency of any aliases.
* Use cdk.Lazy to evaluate changeIds at the end of synth.
---
=> feat(bedrock): method to add deps to PrepareAgent

apidocs/classes/bedrock.Agent.md, apidocs/interfaces/bedrock.AddAgentAliasProps.md, apidocs/modules/bedrock.md, src/cdk-lib/bedrock/agent.ts
Fixes #230 
This change builds on #231 .
Create `AddAgentAliasProps` as a partial copy of `AgentAliasProps` with `aliasName` becoming a required property.
If preferred, this could be implemented with https://github.com/mrgrain/jsii-struct-builder to work around JSII's lack of support for Omit types.
---
=> fix(bedrock): fix addAlias props

src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
This fixes lamba memorySize to be limited by the requested context memory.
---
=> fix: reduce memorySize to context

apidocs/classes/LangchainCommonLayer.md, lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py, lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/helpers/opensearch_helper.py, lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py, lambda/aws-summarization-appsync-stepfn/summary_generator/lambda.py, layers/langchain-common-layer/python/genai_core/adapters/bedrock/ai21_j2.py, layers/langchain-common-layer/python/genai_core/adapters/bedrock/claude.py, layers/langchain-common-layer/python/genai_core/adapters/bedrock/cohere.py, layers/langchain-common-layer/python/genai_core/adapters/bedrock/titan.py, layers/langchain-common-layer/python/genai_core/clients.py, src/patterns/gen-ai/aws-langchain-common-layer/index.ts
This PR contains two refactors:
- Updates how the bedrock client is retrieved to use the boto3 library per the documentation [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock.html).
- Updates aoss indexing to OpenSearchVectorSearch from langchain_community vectorstores as defined [here](https://python.langchain.com/docs/integrations/vectorstores/opensearch#using-aoss-amazon-opensearch-service-serverless).
---
=> chore: update bedrock client retrieval and aoss index creation

apidocs/classes/bedrock.Agent.md, apidocs/interfaces/bedrock.AgentActionGroupProps.md, apidocs/interfaces/bedrock.AgentAliasProps.md, apidocs/interfaces/bedrock.AgentProps.md, lambda/bedrock-custom-resources/custom_resources/__init__.py, lambda/bedrock-custom-resources/custom_resources/bedrock_agent.py, lambda/bedrock-custom-resources/custom_resources/bedrock_agent_action_group.py, lambda/bedrock-custom-resources/custom_resources/bedrock_agent_alias.py, lambda/bedrock-custom-resources/custom_resources/bedrock_agent_knowledgebase.py, lambda/bedrock-custom-resources/custom_resources/bedrock_datasource.py, lambda/bedrock-custom-resources/custom_resources/bedrock_knowledgebase.py, lambda/bedrock-custom-resources/custom_resources/bedrock_prepare_agent.py, src/cdk-lib/bedrock/README.md, src/cdk-lib/bedrock/agent-action-group.ts, src/cdk-lib/bedrock/agent-alias.ts, src/cdk-lib/bedrock/agent.ts, test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap
Per discussions with @massi-ang and the CloudFormation team, there shouldn't be a resource to call PrepareAgent as it doesn't create anything. This change replaces the custom resource with an optional property called `shouldPrepareAgent` that calls and waits for the agent to be prepared after creating or updating the agent, action group, or knowledge base association custom resources.
Alias creation and updates still prepare the agent first. Developers can choose whether to use `shouldPrepareAgent` or create an alias that tracks the latest changes to ensure that their agent is prepared. This change makes the alias custom resource use the same function to prepare the agent and wait as the others.
This change replaces the complicated `changeId` hashes with the `updatedAt` timestamps …
=> feat(bedrock): replace PrepareAgent with shouldPrepareAgent prop

.projen/tasks.json, .projenrc.ts
Fixes #
Add changes required to fix the apidocs generation in the workflow test. Was running successfully on branch https://github.com/awslabs/generative-ai-cdk-constructs/tree/temp/resolve-json-module , and generated a PR (https://github.com/awslabs/generative-ai-cdk-constructs/pull/266) for testing purpose. 
Thanks @scottschreckengaust for your help !
---
=> chore(github): fix code generation workflow

apidocs/classes/CustomSageMakerEndpoint.md, src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md, src/patterns/gen-ai/aws-model-deployment-sagemaker/custom-sagemaker-endpoint.ts
Fixes #
Currently, we force a default value for the volumesizeingb property in the custom sg endpoint. However, for some instance types, this is not supported and fails at deploy time. We now use the value passed through props only if provided
---
=> chore(sg): remove default value for volumesize property

apidocs/interfaces/JumpStartSageMakerEndpointProps.md, src/patterns/gen-ai/aws-model-deployment-sagemaker/README_jumpstart.md, src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.ts, test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-model-deployment-sagemaker.test.ts
Fixes #
- prepend 'jumpstart-' to the endpoint name deployed by the construct
- make the property ```endpoint name``` required 
- update tests and documentation
- tested with the samples through a local build of the constructs, will update the associated sample once this is merged
---
=> chore(construct): SageMaker JumpStart construct endpoint name update

lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt, lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/requirements.txt, lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt, lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt, lambda/aws-summarization-appsync-stepfn/summary_generator/requirements.txt
Fixes #
Bumped langchain version from 0.1.14 to 0.1.11
Bumped dependent langchain-community to <0.1, >0.0.25
---
=> feat(versionupgrade): bump langchain version from 0.1.14 to 0.1.11

lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/__init__.py, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/base/__init__.py, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/base/base.py, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/__init__.py, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/claude.py, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/titan.py, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/registry/__init__.py, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/registry/index.py, lambda/aws-qa-appsync-opensearch/question_answering/src/llms/__init__.py, lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py, lambda/aws-qa-appsync-opensearch/question_answering/src/llms/types.py, lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/chain.py, lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/doc_qa.py, lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/helper.py, lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/image_qa.py, lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt, resources/gen-ai/aws-qa-appsync-opensearch/schema.graphql, resources/gen-ai/aws-rag-appsync-stepfn-opensearch/schema.graphql, src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
Fixes #
- refactor text qa to add support for new models, including Claude v3
- upgrade packages to get access to new upgrades in langchain
- fix issue where model args were not passed to the selected model
- fix graphql schema in rag preventing both qa and rag to be deployed together (conflicting input type)
- improve logging for image qa
Tested with all models supported, rag and long context, and tested image qa
In a next PR, will also refactor the image_qa to support the new structure and add missing models from Bedrock (mistral,...)
Eventually this code will move to a separate package to be used across the constructs
---
=> chore(qa): refactor text qa to add support for additional models and fix issues

lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/base/base.py, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/claude.py, lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/titan.py, lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/doc_qa.py, src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
Fixes #
- Fix issue where streaming is not working properly: variable for streaming was not read correctly
- test with both streaming enabled and disable for several models
- update documentation to include that streaming is supported for qa
Example: 
Test streaming enabled with claude 3 - rag approach. Callback on new llm token correctly called and response generated
---
=> fix(qa): read properly var to fix streaming

lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_index.py
Fixes #349
New KB bedrock indexes use faiss.
CDK:
``` KnowledgeBase/KB: Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (ValidationException) when calling the CreateKnowledgeBase operation: The knowledge base storage configuration provided is invalid... The OpenSearch Serverless engine type associated with your vector index is invalid. Recreate your vector index with one of the following valid engine types: FAISS. Then retry your request.```
New setup from AWS Console
=> fix(bedrock): create index with faiss and l2

.github/workflows/auto-approve.yml, .github/workflows/code-generation.yml, .github/workflows/upgrade-main.yml, projenrc/github-jobs.ts, projenrc/github-workflows.ts
Fixes #
Following the documentation for https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#action-inputs, we cannot use the github action token for auto creation of PRs in our case. Reverting back the bot user to create the PRs automatically, and github-actions bot to auto approve
Now the behavior is the same as the cdk
---
=> chore(github): fix github workflows

apidocs/classes/bedrock.BedrockFoundationModel.md, src/cdk-lib/bedrock/models.ts
Fixes #404 
Add support for claude 3 sonnet and haiku in agents for bedrock
Tested with the bedrock sample available here: https://github.com/aws-samples/generative-ai-cdk-constructs-samples/tree/main/samples/bedrock-agent
Deployed and tested the sample with each one of the new models
---
=> chore(bedrock): add support for claude 3 models in agents for bedrock

lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py
When trying to ingest a file Step function state machine is failing at "generate embeddings from processed documents and store them" with the error : "process_shard() missing 1 required positional argument: model_id" updated code to pass model_id to process_shard() method
Fixes #
Issue - process_shard() missing 1 required positional argument: model_id
---
=> fix: embedding_job is failing to generate embeddings

lambda/bedrock-custom-resources/custom_resources/bedrock_agent_alias.py
Fixes #423 
Fix issue for agent alias name in agent constructor preventing stack deployment
---
=> fix(bedrock): fix agent version issue

apidocs/interfaces/bedrock.AgentProps.md, src/cdk-lib/bedrock/agent.ts
Fixes #
1. Added enableUserInput prop in Agent. (https://github.com/awslabs/generative-ai-cdk-constructs/issues/272)
---
=> feat(construct): added enableUserInput prop on agent

apidocs/classes/bedrock.S3DataSource.md, src/cdk-lib/bedrock/s3-data-source.ts
As described in #470, this pull request attempts to fix the unique ID by defining the `S3DataSource.dataSource` property as `CfnDataSource` construct, and passes the created data source's unique identifier to the `S3DataSource.dataSourceId`.
Fixes #470 
=> fix(bedrock): use CfnDataSource and construct's dataSourceId as unique id (fixes #470)

apidocs/enums/bedrock.ChunkingStrategy.md, src/cdk-lib/bedrock/s3-data-source.ts, test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap, test/cdk-lib/bedrock/s3-data-source.test.ts
Fixes #476
- Fix non deploying data source where chunking strategy is set to DEFAULT
- Add test to cover the use case
- Updated documentation
- Tested by deploying a sample stack
---
=> fix(bedrock): fix default chunking strategy not deploying

.projenrc.ts, apidocs/classes/QaAppsyncOpensearch.md, layers/langchain-common-deps/requirements.txt, src/patterns/gen-ai/aws-langchain-common-layer/index.ts, src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
=> chore(layer): update lambda layer construct and announce deprecation

src/cdk-lib/amazonaurora/README.md, src/cdk-lib/bedrock/README.md, src/cdk-lib/opensearch-vectorindex/README.md, src/cdk-lib/opensearchserverless/README.md, src/cdk-lib/pinecone/README.md
Fixes #604 
`API documentation](../../../apidocs/modules/amazonaurora.md)`
`[API documentation](../../../apidocs/namespaces/amazonaurora/README.md)`
---
=> feat: update API documentation links in README files

.projen/deps.json, .projenrc.ts, CHANGELOG.md, DEVELOPER_GUIDE.md, apidocs/interfaces/DockerLambdaCustomProps.md, apidocs/namespaces/bedrock/README.md, apidocs/namespaces/bedrock/classes/Guardrail.md, apidocs/namespaces/bedrock/enumerations/ContextualGroundingFilterConfigType.md, apidocs/namespaces/bedrock/interfaces/ContextualGroundingPolicyConfigProps.md, apidocs/namespaces/bedrock/interfaces/GuardrailProps.md, package.json, src/cdk-lib/bedrock/README.md, src/cdk-lib/bedrock/content-policy.ts, src/cdk-lib/bedrock/guardrails.ts, src/common/props/DockerLambdaCustomProps.ts, test/cdk-lib/bedrock/guardrails.test.ts, yarn.lock
Fixes #656 
- Update CDK min version to 2.154.1 to support new feature
- Add contextual grounding support
Pending testing
```
guardrails.addContextualGroundingPolicyConfig([
{
threshold: 0.5,
filtersConfigType: bedrock.ContextualGroundingFilterConfigType.GROUNDING,
},
{
threshold: 0.9,
filtersConfigType: bedrock.ContextualGroundingFilterConfigType.RELEVANCE,
},
]);
```
Agent has guardrails attached:
When asking a question with a response factually correct:
Examples when blocking:
---
=> feat(guardrails): add Contextual grounding

.github/workflows/release.yml, .projenrc.ts
Update projen configuration to create a GitHub issue if the release workflow fails
---
=> chore(projen): enable issue creation on release failure

apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md, src/cdk-lib/bedrock/models.ts
Added Opus 3 and Sonnet 3.5 to [BedrockFoundationModel](https://awslabs.github.io/generative-ai-cdk-constructs/apidocs/namespaces/bedrock/classes/BedrockFoundationModel.html).
Note that both models are supported on Agents for Bedrock: https://docs.aws.amazon.com/bedrock/latest/userguide/agents-supported.html
---
=> chore: add missing models (3.5 sonnet and 3 opus)

.github/workflows/build.yml, .github/workflows/release.yml, .mergify.yml, .projen/tasks.json, .projenrc.ts, package.json
This pull request removes packaging and distributing java, because the `JumpStartModel.java` file exceeds the 64K maximum size.
https://github.com/awslabs/generative-ai-cdk-constructs/actions/runs/11861384594/job/33058880785?pr=800
> code too large
---
=> fix: skip java build

apidocs/classes/BedrockCwDashboard.md, apidocs/interfaces/ModelMonitoringProps.md, src/patterns/gen-ai/aws-bedrock-cw-dashboard/README.md, src/patterns/gen-ai/aws-bedrock-cw-dashboard/index.ts
Fixes #
Thanks @jimini55 for the pricing widget !
Update the bedrock CloudWatch dashboard to add the following:
- Missing runtime metrics added recently
- Add default ```= {}``` to props to avoid providing empty brackets if props not provided by user
- Create a CfnOutput with as value the URL of the created cloudwatch dashboard
- Pricing widget for a model if input/output pricing is provided by the user
- Update documentation
Tests:
Also tested to generate 2 dashboards in the same stack to make sure there is no collision in naming/id
---
=> feat(cw): update bedrock cloudwatch dashboard

apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md, src/cdk-lib/bedrock/models.ts
Fixes #834
Add support for https://aws.amazon.com/about-aws/whats-new/2024/12/amazon-nova-foundation-models-bedrock/
Tested by creating 3 agents (one with each model)
---
=> feat(bedrock): add support in agents for nova models

src/cdk-lib/bedrock/agents/agent.ts, test/integ/inference-profiles.integ.snapshot/aws-cdk-bedrock-guardrails-integ-test.assets.json, test/integ/inference-profiles.integ.snapshot/aws-cdk-bedrock-guardrails-integ-test.template.json, test/integ/issue747.integ.snapshot/aws-cdk-bedrock-agents-integ-test.assets.json, test/integ/issue747.integ.snapshot/aws-cdk-bedrock-agents-integ-test.template.json
Fixes #899 
Thanks to @mccauleyp for the investigation. Fixes the issue where some CRIS models cannot be used as there is a missing dependency.
Test:
```
const cris = bedrock.CrossRegionInferenceProfile.fromConfig({
geoRegion: bedrock.CrossRegionInferenceProfileRegion.US,
model: bedrock.BedrockFoundationModel.ANTHROPIC_CLAUDE_3_5_SONNET_V2_0,
});
const agent = new bedrock.Agent(this, 'Agent', {
foundationModel: cris,
instruction: 'You are a helpful and friendly agent that answers questions about agriculture.',
});
```
(Also tested with ***ANTHROPIC_CLAUDE_3_5_HAIKU_V1_0*** and ***ANTHROPIC_CLAUDE_3_5_SONNET_V1_0***)
Deployment succeeds: 
The correct model is used in the console:
The agent is able to perform requests against the model:
The stack is destroyed correctly:
---
By submitting …
=> chore(deps): add dependency to resource for CRIS

.projenrc.ts, package.json, yarn.lock
Signed-off-by: Scott Schreckengaust <scottschreckengaust@users.noreply.github.com>
Fixes #902 
---
=> feat: use node 22

apidocs/namespaces/bedrock/interfaces/AgentAliasProps.md, src/cdk-lib/bedrock/README.md, src/cdk-lib/bedrock/agents/agent-alias.ts
Fixes #947 
Fix collision in default name for agent alias. Thanks to @mccauleyp.
Tested by deploying a first agent+alias, then creating a second alias:
```
const agent = new bedrock.Agent(this, 'Agent', {
foundationModel: bedrock.BedrockFoundationModel.ANTHROPIC_CLAUDE_3_5_SONNET_V1_0,
instruction: 'You are a helpful and friendly agent that answers questions about literature.',
userInputEnabled: true,
shouldPrepareAgent:true
});
new bedrock.AgentAlias(this, 'myalias2', {
agent: agent,
description: 'mytest'
});
new bedrock.AgentAlias(this, 'myalias3', {
agent: agent,
description: 'mytest2',
agentVersion: '2'
});
```
---
=> chore(agent): fix issue with agent alias

.github/workflows/code-generation.yml, .projenrc.ts, CONTRIBUTING.md, DEPRECATION_PROCESS.md, DESIGN_GUIDELINES.md, DEVELOPER_GUIDE.md, README.md, projenrc/github-workflows.ts
Fixes #
- Upgrade PR creation job for code generation workflow to address an intermittent job failure. Same issue as mentioned in this ticket: https://github.com/peter-evans/create-pull-request/issues/2790 
- Update documentation
---
=> chore(PR): doc update and code generation issue

.github/ISSUE_TEMPLATE/rfc.yml, .github/ISSUE_TEMPLATE/support_genai_cdk_constructs.yml
=> chore(issues): add new templates to for issues

.projen/deps.json, .projenrc.ts, CHANGELOG.md, DEVELOPER_GUIDE.md, apidocs/@cdklabs/namespaces/bedrock/README.md, apidocs/@cdklabs/namespaces/bedrock/enumerations/ModalityType.md, apidocs/@cdklabs/namespaces/bedrock/interfaces/ContentFilter.md, package.json, src/cdk-lib/bedrock/guardrails/README.md, src/cdk-lib/bedrock/guardrails/guardrail-filters.ts, yarn.lock
Fixes #1064 
- Upgrade base CDK version to [v2.189.0](https://github.com/aws/aws-cdk/releases/tag/v2.189.0), fixing https://github.com/awslabs/generative-ai-cdk-constructs/security/dependabot/146
- Add support for input/output modalities in Bedrock guardrails content filter
Test:
Using the following code snippet:
```
const guardrail = new bedrock.Guardrail(this, 'bedrockGuardrails', {
name: 'my-BedrockGuardrails',
description: 'Legal ethical guardrails.',
});
guardrail.addContentFilter({
type: ContentFilterType.SEXUAL,
inputStrength: ContentFilterStrength.HIGH,
outputStrength: ContentFilterStrength.MEDIUM,
inputModalities: [ModalityType.TEXT, ModalityType.IMAGE],
outputModalities: [ModalityType.TEXT],
});
```
---
By submitting this pull request, I confirm that you can use, modify, copy, …
=> chore(guardrails): Add support for input/output modalities in Bedrock guardrails content filter

apidocs/@cdklabs/namespaces/bedrock/classes/BedrockFoundationModel.md, src/cdk-lib/bedrock/models.ts
Adds recently added Mistral AI models
https://aws.amazon.com/blogs/aws/aws-announces-pixtral-large-25-02-model-in-amazon-bedrock-serverless/ 
---
=> feat(bedrock): add mistral models

src/cdk-lib/bedrock/agents/README.md, src/cdk-lib/bedrock/agents/agent-alias.ts
Fixes #969
- update the CfnAgentAlias to prevent new alias creation every deployment
- update readme to provide additional information
Testing:
```
const agent = new bedrock.Agent(this, 'Agent', {
foundationModel: bedrock.BedrockFoundationModel.ANTHROPIC_CLAUDE_3_5_SONNET_V1_0,
instruction: 'You are an expert in the field of literature and can provide advice on books.',
userInputEnabled: true,
shouldPrepareAgent:true
});
const agentAlias = new bedrock.AgentAlias(this, 'myalias', {
aliasName: 'my-agent-alias',
agent: agent,
description: 'alias for my agent'
});
```
- Deployed locally and confirmed the agent alias ID.
- Deployed again and confirmed that the agent alias ID had **not changed**, nor the agent version it was pointing to (as I had made no changes). 
- Made a change to the agent …
=> fix(agent): update agent alias
